### ISSUE TITLE
Running LRBinner with several reads files?

### ISSUE THREAD

**Issue by psj1997** [anuradhawick/LRBinner#15]
Hi, 

Thanks for developing this tool.

I have tried to run LRBinner with contig binning. I have one contig file assembled from several samples (~10 samples). How can I use LRBinner for this? For now I have tried and find that when I input 10 reads files to the LRBinner will lead to an error (it is successful with one sample). 

Thanks for your any comments and suggestions.

Sincerely
Shaojun

**Comment by anuradhawick** [comment]
Hi,

This tool currently does not support multiple files. Ideally, you should give one contigs file and one reads the file.

What is your exact use case? Are you dealing with multiple samples?

Sounds to me like you wanted to bin contigs and not reads. Is this the case?

**Comment by psj1997** [comment]
Yes. I have a contig assembled from multiple samples. And I want to bin contigs.

What I use is:

`~/LRBinner/LRBinner contigs --reads-path *.fq --threads 64 --resume --output LRBinner --contigs assembly.fasta`.

How can I use it with multiple samples?

Sincerely
Shaojun

**Comment by anuradhawick** [comment]
You cannot use multiple samples. It is not supported. This was built to bin long reads and the contigs binning part was a hobby feature, so I might not have the bandwidth to extend to your use case very soon.

If you want to use contigs binning please use one of the following from our group. These are actively developed.

1. [https://github.com/metagentools/GraphBin](https://github.com/metagentools/GraphBin)
2. [https://github.com/metagentools/MetaCoAG](https://github.com/metagentools/MetaCoAG)
3. [https://github.com/xuehansheng/RepBin](https://github.com/xuehansheng/RepBin)
4. [https://github.com/metagentools/GraphBin2](https://github.com/metagentools/GraphBin2)

Cheers,
Anuradha

**Comment by psj1997** [comment]
OK. Thanks for your response!

Sincerely
Shaojun
