### ISSUE TITLE
extract bins

### ISSUE THREAD

**Issue by Montmerry** [anuradhawick/LRBinner#16]
Hello, 

I only want to ask if there is a script to extract the bins from the input data with the help of the output of LRBinner bins.txt? 

Thank you in advance for your response

**Comment by anuradhawick** [comment]
Could you have a look at this?

[https://github.com/anuradhawick/LRBinner/blob/main/separate_reads.py](https://github.com/anuradhawick/LRBinner/blob/main/separate_reads.py)

**Comment by Montmery** [comment]
Oh yes, I hadn't seen it. I just tried it and it works great. Thanks a lot.
