### ISSUE TITLE
Lrbinner deleted a directory?

### ISSUE THREAD

**Issue by lidi4** [anuradhawick/LRBinner#17]
Immediately before running lrbinner for the first time, I had examined my general output directory ("Test_Outputs"), which contained organized subdirectories of all my other programs I've run in my pipeline. Then, all I did was run my lrbinner command. It failed, with the error
`FileNotFoundError: [Errno 2] No such file or directory: '/home/lid/Test_Outputs/lrbinner_davinci/checkpoints'`
Then, I typed "ls" from my ~ directory, and the entire Test_Outputs directory had been deleted.

----- I've run it again twice (directing output to a copied directory and making sure everything everywhere is backed up), and it again deleted the directory I sent the output to, even if I make it immediately before sending the command. What is happening here?

My command is simply 
`python lrbinner.py contigs --reads-path ~/Test_Data/SRR12390956.fastq -k 4 -o ~/DavinciOutCopy/DavinciOut/lrbinner --contigs ~/DanvinciOut/racon/polished1_assembly.fasta`

It seems to be coming from
```
 if not resume:
        if os.path.isdir(f"{output}"):
            shutil.rmtree(f"{output}")
        checkpoint = Checkpointer(checkpoints_path)
```

in run_contigs_binning in pipelines.py, but I don't know what the problem is, why nobody else seems to experience this, or how to fix it

I am working on Ubuntu WSL2 if that helps

**Comment by anuradhawick** [comment]
@lidi4 thanks heaps for this issue. This is a bug. I will fix this and get back to you.

I appreciate your patience as I'll be doing this out-side my work hours. :)

**Comment by anuradhawick** [comment]
@lidi4 could you try again? Thanks
