### ISSUE TITLE
Questions about parameter optimization for strict binning

### ISSUE THREAD

**Issue by franciscozorrilla** [anuradhawick/LRBinner#22]
Hello, thank you for developing this tool!

I ran some metagenomic nanopore-based flye assemblies through LRBinner, and then ran the resulting bins through checkm, but its looks like most bins are over 100% conaminated. 
Questions:
1. I was wondering which parameters I should adjust in order to get more strict binning? 
2. Would you expect that binning reads prior to assembly might help me here? 
3. I am also seeing larger genome sizes than expected based on the bin bp content, is this a common issue perhaps related to duplicated contigs?
4. Is there a newer/improved nanopore binning tool that you or others have developed that I should try?

This is the command i used for `lrbinner contig` with default params:
```
ls assemblies/|while read sample;do 
    python LRBinner/LRBinner/lrbinner.py contigs --reads-path fastp/${sample}.fastq -k 3 -t 8 -sep -o bins/${sample} --contigs assemblies/${sample}/assembly.fasta;
done
```
Thanks and best wishes,
Francisco

**Comment by anuradhawick** [comment]
Hello. Thanks for trying this out. 

The contigs binning is not a stable feature. This was initially built for long reads binning. 

You might have better luck trying 

https://github.com/metagentools/MetaCoAG
