### ISSUE TITLE
Build error: ISO C++ 2011 standard

### ISSUE THREAD

**Issue by LynnLy** [anuradhawick/LRBinner#6]
Hi there,

I am trying to build LRBinner within a linux/conda environment as you've described. After running `sh build.sh`, I run into this error:
`#error This file requires compiler and library support for the ISO C++ 2011 standard`
which can be fixed by adding "`-std=c++11`" to the `g++` commands in build.sh, like so:

```bash
echo "BUILDING THE MetaBCC-LR 15 MER COMPUTATIONS"
g++ mbcclr_utils/search-15mers.cpp -fopenmp -lpthread -Wall -o mbcclr_utils/bin/search-15mers -lz -O3 -std=c++11
g++ mbcclr_utils/count-15mers.cpp -fopenmp -lpthread -Wall -o mbcclr_utils/bin/count-15mers -lz -O3 -std=c++11
echo "BUILDING THE MetaBCC-LR 3 MER COMPUTATIONS"
g++ mbcclr_utils/count-kmers.cpp -Wall -fopenmp -lpthread -o mbcclr_utils/bin/count-kmers -lz -O3 -std=c++11
```

I am also trying the contig mode, which required me to downgrade the joblib library, as described [here](https://github.com/scikit-learn-contrib/hdbscan/issues/436):
via `conda install -c conda-forge joblib=0.17.0`

It seems to build properly and run on my data after these changes!

**Comment by anuradhawick** [comment]
Thank you very much for the corrections. I will update the read me with this information. 

The issue with joblib is due to conda  version of hdbscan being outdated. It typically fixes itself when installed through GitHub repo right away. 

I will update the descriptions soon. 

Thanks.
